### ISSUE TITLE
SocialChat v2 Overhaul TODO

### ISSUE THREAD

**Issue by Cosmental** [Cosmental/Social-Chat-V2#1]
**Content Rebuilding:**
- [x] Bubble Chat
- [x] RichText ChatFrame
- [x] "/e {emote}" support
- [x] Role Colors, Names, & Icons

**General Updates:**
- [x] _"Servers are experiencing delays"_ message
- [x] ChatBubble overhead when typing a new message
- [x] SocialChat Default UX (notification sound when a new PRIVATE message appears, chat visibility with button & fading when idle, etc.)
- [x] SocialChat Configurations (eg. Chat Size, TextSize, etc.)
- [x] Extension Builder (must include: Permissions handler to cancel out/change anything in SocialChat, Integration logic to prevent errors, and ensure stability with error feedback)

**General Improvements:**
- [x] RichText multi-layer support
- [x] Offset Sizing -> Scale Sizing to support screen size changes
- [x] Build support for custom UI changes to SocialChat (this includes a custom debugger)

**Extensions:**
- [x] **Emojipedia:** An extension that independently inserts Twemoji into your SocialChat build! You may add your own Emojis along with support for gif emojis!
- [ ] **Rocord:** An extension that simulates Discord with SocialChat! Rocord adds new markdown syntaxing for *spoilers* and username mentions! You can also add reactions to messages, get user details (who they are, icons, etc.), check what time messages were created, and adds additional API integration objects for SocialChat! (these include: _MessageObjects_, _InteractionObjects_, and _AnimationObjects_!)
- [ ] **Autofiller:** An extension that provides autofill simulation into SocialChat! (this is useful for good admin command UX)

**API:**
- [x] ``ChatService.ProcessMessage = function(messageObject : metaTable)`` (allows developers to dynamically accept/reject message requests from clients) [**SERVER ONLY**]
- [x] Markup Developer tools for unique richText markdowns! (based on module configs) [eg. the word ``ex`` gets highlighted in `rgb(255,40,95)`]

**Comment by Cosmental** [comment]
Unmarked tasks will be completed seperately when the time comes! For now, this will only be used for reference.
